# Generated by Django 5.2.17 on 2026-10-06 04:38

import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_branchmanager_branchstaff"),
        ("fleet", "0001_initial"),
        ("pricing", "0001_initial"),
    ]

    operations = [
        # Reliability-1: the vehicle '=' part of the exclusion constraint needs
        # btree_gist, so the extension must exist before the Booking table.
        BtreeGistExtension(),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking_reference", models.CharField(blank=True, max_length=18)),
                ("pickup_datetime", models.DateTimeField()),
                ("return_datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Pending Payment", "Pending Payment"),
                            ("Confirmed", "Confirmed"),
                            ("Active", "Active"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                            ("No-show", "No-show"),
                        ],
                        default="Draft",
                        max_length=32,
                    ),
                ),
                (
                    "pickup_code",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        validators=[django.core.validators.RegexValidator("^[0-9]{6}$")],
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("delivery_address", models.TextField(blank=True)),
                ("delivery_pincode", models.CharField(blank=True, max_length=6)),
                ("hold_expires_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("safety_notice_acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("handed_over_at", models.DateTimeField(blank=True, null=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("distance_travelled", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "blocked_period",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(editable=False),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="accounts.customer",
                    ),
                ),
                (
                    "pickup_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="fleet.branch",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="pricing.tariff",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-pickup_datetime"],
            },
        ),
        migrations.CreateModel(
            name="BookingAddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("detail", models.CharField(blank=True, max_length=150)),
                (
                    "add_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_lines",
                        to="pricing.addon",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="add_ons",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "booking add-on",
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer", "-pickup_datetime"], name="bookings_bo_custome_6d5c59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["pickup_branch", "pickup_datetime"], name="bookings_bo_pickup__645c01_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status__in", ["Pending Payment", "Confirmed", "Active"])),
                expressions=[("vehicle", "="), ("blocked_period", "&&")],
                name="bookings_no_overlapping_vehicle_blocks",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("return_datetime__gt", models.F("pickup_datetime"))),
                name="bookings_return_after_pickup",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("booking_reference", ""), _negated=True),
                fields=("booking_reference",),
                name="bookings_reference_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("booking_reference", ""),
                    ("booking_reference__regex", "^VRMS-[0-9]{8}-[0-9]{4}$"),
                    _connector="OR",
                ),
                name="bookings_reference_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pickup_code", ""), ("pickup_code__regex", "^[0-9]{6}$"), _connector="OR"
                ),
                name="bookings_pickup_code_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0), ("security_deposit__gte", 0)),
                name="bookings_amounts_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingaddon",
            constraint=models.UniqueConstraint(
                fields=("booking", "add_on"), name="bookings_addon_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingaddon",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1), ("daily_rate__gte", 0)),
                name="bookings_addon_quantity_and_rate",
            ),
        ),
    ]
