# Generated by Django 5.2.17 on 2026-10-06 04:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("Email", "Email"), ("SMS", "SMS"), ("Push", "Push")], max_length=8
                    ),
                ),
                (
                    "destination",
                    models.CharField(help_text="E-mail, mobile or device token.", max_length=254),
                ),
                ("template", models.CharField(max_length=100)),
                ("template_version", models.PositiveSmallIntegerField(default=1)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Queued", "Queued"),
                            ("Sent", "Sent"),
                            ("Delivered", "Delivered"),
                            ("Failed", "Failed"),
                        ],
                        default="Queued",
                        max_length=16,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=128)),
                ("error", models.CharField(blank=True, max_length=255)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("queued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="bookings.booking",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "queued_at"], name="notificatio_status_23fd9e_idx"
                    )
                ],
            },
        ),
    ]
