# Generated by Django 5.2.17 on 2026-10-06 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_branchmanager_branchstaff"),
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        choices=[("Car", "Car"), ("Two-Wheeler", "Two-Wheeler")],
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "add-on",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("daily_rate__gte", 0)),
                        name="pricing_addon_rate_not_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FuelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("Petrol", "Petrol"),
                            ("Diesel", "Diesel"),
                            ("CNG", "CNG"),
                            ("Electric", "Electric"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Per litre, per kg (CNG) or per kWh (electric).",
                        max_digits=12,
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                (
                    "defined_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fuel_prices",
                        to="accounts.administrator",
                    ),
                ),
            ],
            options={
                "ordering": ["fuel_type", "-effective_from"],
                "get_latest_by": "effective_from",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fuel_type", "effective_from"),
                        name="pricing_fuelprice_unique_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price_per_unit__gte", 0)),
                        name="pricing_fuelprice_not_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("weekly_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("security_deposit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "free_km_allowance",
                    models.PositiveIntegerField(help_text="Kilometres per rental day."),
                ),
                ("excess_km_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("effective_from", models.DateTimeField()),
                (
                    "defined_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tariffs",
                        to="accounts.administrator",
                    ),
                ),
                (
                    "vehicle_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tariffs",
                        to="fleet.vehiclecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["vehicle_category", "-effective_from"],
                "get_latest_by": "effective_from",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vehicle_category", "effective_from"),
                        name="pricing_tariff_unique_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("hourly_rate__gte", 0),
                            ("daily_rate__gte", 0),
                            ("weekly_rate__gte", 0),
                            ("security_deposit__gte", 0),
                            ("excess_km_rate__gte", 0),
                        ),
                        name="pricing_tariff_amounts_not_negative",
                    ),
                ],
            },
        ),
    ]
