# Generated by Django 5.2.17 on 2026-10-06 15:29

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("Percent", "Percent"), ("Fixed", "Fixed")], max_length=16
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percent (0-100) or a fixed amount.",
                        max_digits=12,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Empty for unlimited use.", null=True
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("code"),
                        name="pricing_discountcode_code_ci_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("value__gt", 0)),
                        name="pricing_discountcode_value_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("discount_type", "Percent"), _negated=True),
                            ("value__lte", 100),
                            _connector="OR",
                        ),
                        name="pricing_discountcode_percent_max_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valid_to__gt", models.F("valid_from"))),
                        name="pricing_discountcode_valid_window",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("usage_limit__isnull", True),
                            ("times_used__lte", models.F("usage_limit")),
                            _connector="OR",
                        ),
                        name="pricing_discountcode_within_usage_limit",
                    ),
                ],
            },
        ),
    ]
