# Generated by Django 5.2.17 on 2026-10-06 04:32

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# Append-only enforcement (CLAUDE.md, SE-10, Pay.Ledger, Pay.Invoice).
# vrms_reject_modification() is shared by every append-only table; each
# table gets its own BEFORE UPDATE OR DELETE trigger. TRUNCATE (used only by
# test teardown and explicit resets) is not a row operation and is unaffected.
REJECT_FUNCTION_SQL = """
CREATE OR REPLACE FUNCTION vrms_reject_modification() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'VRMS: % on append-only table % is not permitted', TG_OP, TG_TABLE_NAME
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
"""
REJECT_FUNCTION_REVERSE_SQL = "DROP FUNCTION IF EXISTS vrms_reject_modification();"

AUDITLOG_TRIGGER_SQL = """
CREATE TRIGGER core_auditlog_append_only
BEFORE UPDATE OR DELETE ON core_auditlog
FOR EACH ROW EXECUTE FUNCTION vrms_reject_modification();
"""
AUDITLOG_TRIGGER_REVERSE_SQL = "DROP TRIGGER IF EXISTS core_auditlog_append_only ON core_auditlog;"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.CharField(max_length=64)),
                (
                    "before",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "after",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("prev_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("entry_hash", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty for actions taken by the system itself.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="core_auditl_entity__244637_idx"
                    )
                ],
            },
        ),
        migrations.RunSQL(REJECT_FUNCTION_SQL, REJECT_FUNCTION_REVERSE_SQL),
        migrations.RunSQL(AUDITLOG_TRIGGER_SQL, AUDITLOG_TRIGGER_REVERSE_SQL),
    ]
