/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Returns the access token (5 minutes) and the user, and sets the refresh cookie (30 minutes). The refresh token is never in a response body (D21). It is set as the httpOnly, SameSite=Strict cookie `vrms_refresh`, scoped to /api/v1/auth/, which the browser sends back automatically. Keep the access token in memory only.
         */
        post: operations["api_v1_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description No request body and no access token needed. Blacklists the refresh token in the cookie, if any, and always clears the cookie. The refresh token is never in a response body (D21). It is set as the httpOnly, SameSite=Strict cookie `vrms_refresh`, scoped to /api/v1/auth/, which the browser sends back automatically. Keep the access token in memory only.
         */
        post: operations["api_v1_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change password
         * @description Change the password; every session ends and the user signs in again.
         */
        post: operations["api_v1_auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh the access token
         * @description No request body. Reads the refresh cookie, blacklists it, sets a new one and returns a new access token and the user (also used to restore a session when the page loads). 401 with code `session_ended` when the cookie is missing, expired or already used; the cookie is then cleared. The refresh token is never in a response body (D21). It is set as the httpOnly, SameSite=Strict cookie `vrms_refresh`, scoped to /api/v1/auth/, which the browser sends back automatically. Keep the access token in memory only.
         */
        post: operations["api_v1_auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register as a customer
         * @description SE-7: create an inactive customer account and send an OTP by SMS.
         */
        post: operations["api_v1_auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-otp/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend the registration OTP
         * @description Send a new registration code; the previous one stops working.
         */
        post: operations["api_v1_auth_resend_otp_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-otp/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify the registration OTP
         * @description SE-7: verify the registration code and activate the account.
         */
        post: operations["api_v1_auth_verify_otp_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{token}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a stored file through a signed link (SI-3)
         * @description Serve one stored file to whoever holds a valid, unexpired link.
         *
         *     The signature is the credential, so no session or token is needed; a
         *     forged or expired link gets a 404 that says nothing about the file.
         */
        get: operations["api_v1_files_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Liveness and readiness check, also the source of the agency name (D7).
         *
         *     Public on purpose: used by deployment health checks and by the home page
         *     before anyone signs in. It exposes no user or business data.
         */
        get: operations["api_v1_health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/licence/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My driving licence
         * @description The customer's own driving licence (Book.Eligible.No: submit a licence now).
         */
        get: operations["api_v1_licence_retrieve"];
        put?: never;
        /**
         * Submit or resubmit my driving licence
         * @description Multipart form. Both images are required (Appendix A front and back image): JPG or PNG, at most 5 MB. An already-expired licence is refused (BR-2). The licence then awaits verification by branch staff or an administrator.
         */
        post: operations["api_v1_licence_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/licences/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Licences pending verification
         * @description Licences awaiting verification, oldest first.
         *
         *     Licences are not tied to a branch, so every branch's staff see the queue.
         */
        get: operations["api_v1_licences_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/licences/{id}/approve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a licence */
        post: operations["api_v1_licences_approve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/licences/{id}/reject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a licence (a reason is required) */
        post: operations["api_v1_licences_reject_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My profile
         * @description The signed-in user's own profile.
         */
        get: operations["api_v1_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update my profile
         * @description Name and address change at once. A new mobile number is applied only after the code sent to it is confirmed at /api/v1/me/verify-mobile/ (SE-7).
         */
        patch: operations["api_v1_me_partial_update"];
        trace?: never;
    };
    "/api/v1/me/verify-mobile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a new mobile number
         * @description SE-7: confirm a new mobile number with the code sent to it.
         */
        post: operations["api_v1_me_verify_mobile_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Sign-in and refresh response (D21): the refresh token is in the cookie only. */
        AccessToken: {
            access: string;
            user: components["schemas"]["UserSummary"];
        };
        /**
         * @description * `Car` - Car
         *     * `Two-Wheeler` - Two-Wheeler
         * @enum {string}
         */
        CategoriesEnum: "Car" | "Two-Wheeler";
        /**
         * @description * `ok` - ok
         *     * `unreachable` - unreachable
         * @enum {string}
         */
        DatabaseEnum: "ok" | "unreachable";
        Detail: {
            detail: string;
        };
        Email: {
            /** Format: email */
            email: string;
        };
        Health: {
            status: components["schemas"]["HealthStatusEnum"];
            database: components["schemas"]["DatabaseEnum"];
            agency_name: string;
            currency: string;
        };
        /**
         * @description * `ok` - ok
         *     * `degraded` - degraded
         * @enum {string}
         */
        HealthStatusEnum: "ok" | "degraded";
        /** @description A licence as its owner, branch staff and administrators see it. */
        Licence: {
            readonly id: number;
            readonly licence_number: string;
            readonly issuing_authority: string;
            /** Format: date */
            readonly issue_date: string | null;
            /** Format: date */
            readonly expiry_date: string | null;
            readonly categories: string[];
            readonly status: components["schemas"]["LicenceStatusEnum"];
            readonly rejection_reason: string;
            /** Format: date-time */
            readonly verified_at: string | null;
            readonly front_image_url: string | null;
            readonly back_image_url: string | null;
            /** Format: date-time */
            readonly updated_at: string;
        };
        LicenceCustomer: {
            customer_id: number;
            name: string;
            /** Format: email */
            email: string;
            mobile_no: string;
            /** Format: date */
            date_of_birth: string;
        };
        LicenceReject: {
            reason: string;
        };
        /** @description For verification: the licence plus the customer it belongs to (BR-2). */
        LicenceReview: {
            readonly id: number;
            readonly licence_number: string;
            readonly issuing_authority: string;
            /** Format: date */
            readonly issue_date: string | null;
            /** Format: date */
            readonly expiry_date: string | null;
            readonly categories: string[];
            readonly status: components["schemas"]["LicenceStatusEnum"];
            readonly rejection_reason: string;
            /** Format: date-time */
            readonly verified_at: string | null;
            readonly front_image_url: string | null;
            readonly back_image_url: string | null;
            /** Format: date-time */
            readonly updated_at: string;
            readonly customer: components["schemas"]["LicenceCustomer"];
        };
        /**
         * @description * `Not Submitted` - Not Submitted
         *     * `Pending Verification` - Pending Verification
         *     * `Verified` - Verified
         *     * `Rejected` - Rejected
         *     * `Expired` - Expired
         * @enum {string}
         */
        LicenceStatusEnum: "Not Submitted" | "Pending Verification" | "Verified" | "Rejected" | "Expired";
        /** @description Appendix A licence: number, authority, 1:m category, dates, both images. */
        LicenceSubmit: {
            licence_number: string;
            issuing_authority: string;
            /** Format: date */
            issue_date: string;
            /** Format: date */
            expiry_date: string;
            categories: components["schemas"]["CategoriesEnum"][];
            /**
             * Format: uri
             * @description JPG or PNG image, at most 5 MB (Appendix A front/back image).
             */
            front_image: string;
            /**
             * Format: uri
             * @description JPG or PNG image, at most 5 MB (Appendix A front/back image).
             */
            back_image: string;
        };
        Login: {
            /** Format: email */
            email: string;
            password: string;
        };
        OTPCode: {
            code: string;
        };
        PaginatedLicenceReviewList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["LicenceReview"][];
        };
        PasswordChange: {
            current_password: string;
            new_password: string;
        };
        PatchedProfileUpdate: {
            name?: string;
            mobile_no?: string;
            address?: string;
        };
        Profile: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly name: string;
            readonly mobile_no: string;
            readonly address: string;
            readonly role: components["schemas"]["RoleEnum"];
        };
        ProfileUpdateResponse: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly name: string;
            readonly mobile_no: string;
            readonly address: string;
            readonly role: components["schemas"]["RoleEnum"];
            mobile_change_pending: boolean;
        };
        Register: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
            mobile_no: string;
            address: string;
            /** Format: date */
            date_of_birth: string;
            emergency_contact_name: string;
            emergency_contact_mobile: string;
        };
        RegisterResponse: {
            /** Format: email */
            email: string;
            detail: string;
        };
        /**
         * @description * `CUSTOMER` - Customer
         *     * `BRANCH_STAFF` - Branch Staff
         *     * `MAINTENANCE_TECHNICIAN` - Maintenance Technician
         *     * `ADMINISTRATOR` - Administrator
         *     * `BRANCH_MANAGER` - Branch Manager
         * @enum {string}
         */
        RoleEnum: "CUSTOMER" | "BRANCH_STAFF" | "MAINTENANCE_TECHNICIAN" | "ADMINISTRATOR" | "BRANCH_MANAGER";
        UserSummary: {
            readonly id: number;
            /** Format: email */
            email: string;
            name: string;
            role?: components["schemas"]["RoleEnum"];
        };
        VerifyOTP: {
            /** Format: email */
            email: string;
            code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_v1_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description Account locked (SE-8) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    api_v1_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChange"];
                "multipart/form-data": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description Invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    api_v1_auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_auth_resend_otp_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Email"];
                "application/x-www-form-urlencoded": components["schemas"]["Email"];
                "multipart/form-data": components["schemas"]["Email"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    api_v1_auth_verify_otp_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOTP"];
                "application/x-www-form-urlencoded": components["schemas"]["VerifyOTP"];
                "multipart/form-data": components["schemas"]["VerifyOTP"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    api_v1_files_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    api_v1_licence_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Licence"];
                };
            };
        };
    };
    api_v1_licence_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["LicenceSubmit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Licence"];
                };
            };
            /** @description Invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_licences_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLicenceReviewList"];
                };
            };
        };
    };
    api_v1_licences_approve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LicenceReview"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_licences_reject_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LicenceReject"];
                "application/x-www-form-urlencoded": components["schemas"]["LicenceReject"];
                "multipart/form-data": components["schemas"]["LicenceReject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LicenceReview"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    api_v1_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfileUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfileUpdate"];
                "multipart/form-data": components["schemas"]["PatchedProfileUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileUpdateResponse"];
                };
            };
        };
    };
    api_v1_me_verify_mobile_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OTPCode"];
                "application/x-www-form-urlencoded": components["schemas"]["OTPCode"];
                "multipart/form-data": components["schemas"]["OTPCode"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
}
