# Generated by Django 5.2.17 on 2026-10-06 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_branchmanager_branchstaff"),
        ("fleet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Preventive", "Preventive"),
                            ("Corrective", "Corrective"),
                            ("Inspection", "Inspection"),
                            ("Cleaning", "Cleaning"),
                            ("Documentation", "Documentation"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Reported", "Reported"),
                            ("Scheduled", "Scheduled"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Reported",
                        max_length=16,
                    ),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("reported_problem", models.TextField()),
                ("scheduled_from", models.DateTimeField(blank=True, null=True)),
                ("scheduled_to", models.DateTimeField(blank=True, null=True)),
                ("service_date", models.DateField(blank=True, null=True)),
                ("odometer_at_service", models.PositiveIntegerField(blank=True, null=True)),
                ("work_description", models.TextField(blank=True)),
                ("labour_cost", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "workshop_invoice",
                    models.FileField(blank=True, upload_to="maintenance/invoices/"),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_jobs",
                        to="accounts.maintenancetechnician",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_jobs",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartUsed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("part_name", models.CharField(max_length=150)),
                ("quantity", models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="maintenance.maintenancejob",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "parts used",
            },
        ),
        migrations.AddIndex(
            model_name="maintenancejob",
            index=models.Index(fields=["vehicle", "status"], name="maintenance_vehicle_cbf3e5_idx"),
        ),
        migrations.AddConstraint(
            model_name="maintenancejob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scheduled_from__isnull", True),
                    ("scheduled_to__isnull", True),
                    ("scheduled_to__gt", models.F("scheduled_from")),
                    _connector="OR",
                ),
                name="maintenance_schedule_ends_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancejob",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_cost__gte", 0), ("labour_cost__gte", 0)),
                name="maintenance_costs_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="partused",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0), ("unit_cost__gte", 0)),
                name="maintenance_part_quantity_and_cost",
            ),
        ),
    ]
