# Generated by Django 5.2.17 on 2026-10-06 04:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("branch_name", models.CharField(max_length=100, unique=True)),
                ("address", models.TextField()),
            ],
            options={
                "verbose_name_plural": "branches",
                "ordering": ["branch_name"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("registration_no", models.CharField(max_length=16, unique=True)),
                ("brand", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=64)),
                ("odometer", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("On Rent", "On Rent"),
                            ("Under Maintenance", "Under Maintenance"),
                            ("Unsafe", "Unsafe"),
                            ("Retired", "Retired"),
                        ],
                        default="Available",
                        max_length=32,
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1990),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                ("colour", models.CharField(max_length=32)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("Petrol", "Petrol"),
                            ("Diesel", "Diesel"),
                            ("CNG", "CNG"),
                            ("Electric", "Electric"),
                        ],
                        max_length=16,
                    ),
                ),
                ("chassis_number", models.CharField(max_length=32, unique=True)),
                ("available_from", models.DateField()),
                ("last_service_date", models.DateField(blank=True, null=True)),
                ("last_service_odometer", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fuel_capacity",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "home_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="fleet.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["registration_no"],
            },
        ),
        migrations.CreateModel(
            name="VehicleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("Car", "Car"), ("Two-Wheeler", "Two-Wheeler")], max_length=16
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "vehicle categories",
                "ordering": ["vehicle_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "vehicle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="fleet.vehicle",
                    ),
                ),
                ("seating_capacity", models.PositiveSmallIntegerField()),
                (
                    "transmission",
                    models.CharField(
                        choices=[("Manual", "Manual"), ("Automatic", "Automatic")], max_length=16
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("fleet.vehicle",),
        ),
        migrations.CreateModel(
            name="TwoWheeler",
            fields=[
                (
                    "vehicle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="fleet.vehicle",
                    ),
                ),
                ("engine_cc", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("fleet.vehicle",),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles",
                to="fleet.vehiclecategory",
            ),
        ),
        migrations.CreateModel(
            name="VehicleDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("Insurance", "Insurance"),
                            ("Pollution Certificate", "Pollution Certificate"),
                            ("Fitness Certificate", "Fitness Certificate"),
                            ("Road Tax", "Road Tax"),
                        ],
                        max_length=32,
                    ),
                ),
                ("document_number", models.CharField(blank=True, max_length=64)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField()),
                ("file", models.FileField(blank=True, upload_to="vehicles/documents/")),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["vehicle", "document_type", "-expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="VehiclePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.FileField(upload_to="vehicles/photos/")),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["vehicle", "position"],
            },
        ),
        migrations.CreateModel(
            name="BranchServiceableArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pincode",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{6}$", "A pincode is six digits."
                            )
                        ],
                    ),
                ),
                ("locality", models.CharField(blank=True, max_length=100)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serviceable_areas",
                        to="fleet.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["branch", "pincode"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch", "pincode", "locality"),
                        name="fleet_serviceablearea_unique",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["home_branch", "status"], name="fleet_vehic_home_br_d2b22c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("last_service_odometer__isnull", True),
                    ("last_service_odometer__lte", models.F("odometer")),
                    _connector="OR",
                ),
                name="fleet_vehicle_service_odometer_not_ahead",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicledocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    ("expiry_date__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="fleet_vehicledocument_valid_period",
            ),
        ),
    ]
