# Generated by Django 5.2.17 on 2026-10-06 04:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_branchmanager_branchstaff"),
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[("Handover", "Handover"), ("Return", "Return")], max_length=16
                    ),
                ),
                ("odometer_reading", models.PositiveIntegerField()),
                (
                    "fuel_level",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percent of a full tank or battery.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("signature", models.FileField(blank=True, upload_to="rentals/signatures/")),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("accessories", models.JSONField(blank=True, default=list)),
                ("damage_marks", models.JSONField(blank=True, default=list)),
                ("odometer_override_reason", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="condition_reports",
                        to="bookings.booking",
                    ),
                ),
                (
                    "odometer_override_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="odometer_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="condition_reports",
                        to="accounts.branchstaff",
                    ),
                ),
            ],
            options={
                "ordering": ["booking", "recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="ConditionPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.FileField(upload_to="rentals/photos/")),
                ("caption", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="rentals.conditionreport",
                    ),
                ),
            ],
            options={
                "ordering": ["report", "uploaded_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="conditionreport",
            constraint=models.UniqueConstraint(
                fields=("booking", "report_type"), name="rentals_one_report_per_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="conditionreport",
            constraint=models.CheckConstraint(
                condition=models.Q(("fuel_level__gte", 0), ("fuel_level__lte", 100)),
                name="rentals_fuel_level_percent",
            ),
        ),
    ]
