# Generated by Django 5.2.17 on 2026-10-06 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("admin_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date_of_birth", models.DateField()),
                ("is_blacklisted", models.BooleanField(default=False)),
                (
                    "outstanding_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("emergency_contact_name", models.CharField(max_length=150)),
                ("emergency_contact_mobile", models.CharField(max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("licence_number", models.CharField(blank=True, max_length=32)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Submitted", "Not Submitted"),
                            ("Pending Verification", "Pending Verification"),
                            ("Verified", "Verified"),
                            ("Rejected", "Rejected"),
                            ("Expired", "Expired"),
                        ],
                        default="Not Submitted",
                        max_length=32,
                    ),
                ),
                ("issuing_authority", models.CharField(blank=True, max_length=150)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("front_image", models.FileField(blank=True, upload_to="licences/")),
                ("back_image", models.FileField(blank=True, upload_to="licences/")),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licence",
                        to="accounts.customer",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licences_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LicenceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("Car", "Car"), ("Two-Wheeler", "Two-Wheeler")], max_length=16
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="accounts.licence",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "licence categories",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTechnician",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("technician_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("workshop", models.CharField(max_length=150)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_technician",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OneTimePassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("Registration", "Registration"),
                            ("Mobile Change", "Mobile Change"),
                            ("Email Change", "Email Change"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "destination",
                    models.CharField(help_text="Mobile number or e-mail address.", max_length=254),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_time_passwords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(("outstanding_due__gte", 0)),
                name="accounts_customer_due_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="licence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("licence_number", ""), _negated=True),
                fields=("licence_number",),
                name="accounts_licence_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="licencecategory",
            constraint=models.UniqueConstraint(
                fields=("licence", "category"), name="accounts_licencecategory_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="onetimepassword",
            index=models.Index(
                fields=["user", "purpose", "-created_at"], name="accounts_on_user_id_4c0bff_idx"
            ),
        ),
    ]
