# Generated by Django 5.2.17 on 2026-10-06 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profiles_licence_otp"),
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchManager",
            fields=[
                (
                    "administrator_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounts.administrator",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managers",
                        to="fleet.branch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("accounts.administrator",),
        ),
        migrations.CreateModel(
            name="BranchStaff",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("staff_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff",
                        to="fleet.branch",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "branch staff",
            },
        ),
    ]
