# Generated by Django 5.2.17 on 2026-10-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_branchmanager_branchstaff"),
    ]

    operations = [
        migrations.AddField(
            model_name="licence",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
