# Generated by Django 5.2.17 on 2026-10-06 04:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# Pay.Invoice, Pay.Ledger, History.Immutable: issued invoices, their lines and
# adjustments, and ledger entries are append-only. vrms_reject_modification()
# comes from core.0001_initial.
APPEND_ONLY_TABLES = [
    "payments_invoice",
    "payments_invoiceline",
    "payments_invoiceadjustment",
    "payments_ledgerentry",
]


def _trigger(table: str) -> migrations.RunSQL:
    return migrations.RunSQL(
        f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
        "FOR EACH ROW EXECUTE FUNCTION vrms_reject_modification();",
        f"DROP TRIGGER IF EXISTS {table}_append_only ON {table};",
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_branchmanager_branchstaff"),
        ("bookings", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.CharField(max_length=64, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Initiated", "Initiated"),
                            ("Processing", "Processing"),
                            ("Succeeded", "Succeeded"),
                            ("Failed", "Failed"),
                            ("Reversed", "Reversed"),
                        ],
                        default="Initiated",
                        max_length=32,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("Authorize", "Authorize"),
                            ("Capture", "Capture"),
                            ("Refund", "Refund"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("Rental", "Rental"),
                            ("Security Deposit", "Security Deposit"),
                            ("Due", "Due"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("gateway_reference", models.CharField(blank=True, max_length=128)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_ups",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CardPayment",
            fields=[
                (
                    "payment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.payment",
                    ),
                ),
                ("card_token", models.CharField(max_length=255)),
                ("card_brand", models.CharField(max_length=32)),
            ],
            options={
                "abstract": False,
            },
            bases=("payments.payment",),
        ),
        migrations.CreateModel(
            name="OnlinePayment",
            fields=[
                (
                    "payment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.payment",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("UPI", "UPI"),
                            ("Net Banking", "Net Banking"),
                            ("Wallet", "Wallet"),
                        ],
                        max_length=16,
                    ),
                ),
                ("upi_id", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("payments.payment",),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("invoice_number", models.CharField(max_length=32, unique=True)),
                ("issue_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("agency_name", models.CharField(max_length=150)),
                ("agency_tax_registration", models.CharField(blank=True, max_length=64)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="bookings.booking",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("adjustment_number", models.CharField(max_length=32, unique=True)),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[("Credit Note", "Credit Note"), ("Debit Note", "Debit Note")],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="payments.invoice",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_adjustments_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("Rental", "Rental"),
                            ("Add-on", "Add-on"),
                            ("Excess Kilometres", "Excess Kilometres"),
                            ("Fuel Shortfall", "Fuel Shortfall"),
                            ("Late Return", "Late Return"),
                            ("Unreturned Accessory", "Unreturned Accessory"),
                            ("Damage", "Damage"),
                            ("Discount", "Discount"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("justification", models.TextField(blank=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="payments.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("Charge", "Charge"),
                            ("Capture", "Capture"),
                            ("Refund", "Refund"),
                            ("Deposit Hold", "Deposit Hold"),
                            ("Deposit Release", "Deposit Release"),
                            ("Adjustment", "Adjustment"),
                        ],
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[("Card", "Card"), ("Online", "Online"), ("Cash", "Cash")],
                        max_length=16,
                    ),
                ),
                ("gateway_reference", models.CharField(blank=True, max_length=128)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="bookings.booking",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="payments.payment",
                    ),
                ),
                (
                    "reference_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="payments.ledgerentry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ledger entries",
                "ordering": ["booking", "timestamp", "id"],
            },
        ),
        migrations.CreateModel(
            name="CashPayment",
            fields=[
                (
                    "payment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.payment",
                    ),
                ),
                ("customer_acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_payments",
                        to="accounts.branchstaff",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("payments.payment",),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payments_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", 0), ("total_amount__gte", 0)),
                name="payments_invoice_amounts_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0), ("tax_amount__gte", 0)),
                name="payments_adjustment_amounts",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("line_type", "Discount"), ("amount__lte", 0)),
                    models.Q(
                        models.Q(("line_type", "Discount"), _negated=True), ("amount__gte", 0)
                    ),
                    _connector="OR",
                ),
                name="payments_invoiceline_amount_sign",
            ),
        ),
        *[_trigger(table) for table in APPEND_ONLY_TABLES],
    ]
